### ISSUE TITLE
v0.2.9 release

### ISSUE THREAD

**Issue by scottkidder** [Cropster/ember-visual-test#22]
Hello, I've noticed that v0.2.9 is unpublished and is listed as a release with no public facing changes. However it appears there several improvements from @hakubo in the v0.2.9 release. Can we publish this release or cut a new release?

Thanks,
Scott

**Comment by mydea** [comment]
Hey,

I've just released 0.2.10, which also includes a fix for the blueprint. Sorry, that slipped my mind ;)

**Comment by scottkidder** [comment]
Thanks @mydea
