### ISSUE TITLE
Feature Idea: Viewer app for visual-test-output

### ISSUE THREAD

**Issue by scottkidder** [Cropster/ember-visual-test#23]
I've been wondering if there is any interest in creating an app to act as a viewer for both baselines and diffs that could be used in development, and maybe deployed for internal reviews, etc.

I'm thinking that it could be similar to the viewer included with [ember-svg-jar](https://github.com/ivanvotti/ember-svg-jar)

Let me know if there is any interest and we could lay out a roadmap.

**Comment by mydea** [comment]
Hey,

yeah, that sounds like a great idea. Would absolutely love to accept a PR with such a functionality.
Let me know if there is anything I can do to help.

**Comment by scottkidder** [comment]
Closing because I'll likely never have the bandwidth to do this alone and I've developed a pretty good console based workflow. I'll be happy to help if there is ever any other interest.
