### ISSUE TITLE
Approve all in CLI?

### ISSUE THREAD

**Issue by jembezmamy** [Cropster/ember-visual-test#24]
I've noticed I constantly repeat the same process: I review changes in `diff` folder and when everything looks ok, I copy changed files from `tmp` to `baseline`. Sometimes they are in nested catalogs which makes the whole process so tedious...

I feel something like `ember visual-test:approve` would be useful for me. It should just replace current baseline images with tmp - but only for changed images. And then clean the `diff` and `tmp` folders.

It would be somehow similar to `visual-test:reset` but much faster and it would ignore small changes (below diff threshold).

What do you think?

**Comment by mydea** [comment]
Hmm, I guess that could be useful. Would you like to work on a PR for that?

**Comment by jembezmamy** [comment]
Ok! I'll do it.
