### ISSUE TITLE
Seeing Error: Browser disconnected

### ISSUE THREAD

**Issue by scottkidder** [Cropster/ember-visual-test#6]
I hit this once I ran a few tests that were capturing with my entire test suite. It's like testem is weirded out that the headless chrome that is started by this addon is shutdown by something other than it, so it counts as a test error.

UPDATE:
I finally discovered browser_disconnect_timeout which appears to fix the issue when set high enough that testem doesn't count our headless chrome instances being gone as a failure.

testem.js

```
browser_disconnect_timeout: 120,
```

**Comment by mydea** [comment]
Good catch, I saw that a few times as well. Will put that in the readme!
